/// <reference types="next/image-types/global" />

// Declares static image imports (`import img from "./photo.webp"`) as
// StaticImageData, used by the homepage photo panels.
//
// Next normally supplies this via next-env.d.ts — but that file is generated by
// `next build`/`next dev` and is gitignored here (.gitignore:9), while CI runs
// `pnpm typecheck` *before* `pnpm build`. On a fresh checkout the declaration
// therefore does not exist yet and static image imports fail to resolve, even
// though the same command passes on any machine that has built once.
//
// Tracking it here makes typecheck independent of build order and of generated
// files. Do not delete without also reordering the CI steps.
